- id: backup config
  alias: backup config
  trigger:
    platform: time
    at: 02:00:00
  action:
    service: shell_command.save_config
- id: '1567537848073'
  alias: Alerte intrusion
  trigger:
  - entity_id: binary_sensor.door_window_sensor_chambre_bas
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.door_window_sensor_cuisine
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.door_window_sensor_devant
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.door_window_sensor_terrasse
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: person.alice
    state: not_home
  - condition: state
    entity_id: person.florent
    state: not_home
  action:
  - data:
      message: Une porte ou une fenetre est ouverte mais personne n'est présent
      title: Alerte intrusion
    service: notify.email
- id: '1568061925733'
  alias: Backup
  trigger:
  - hours: '2'
    minutes: '30'
    platform: time_pattern
    seconds: '0'
  condition: []
  action:
  - service: hassio.snapshot_full
- id: '1568229466238'
  alias: chauffage antoine on
  trigger:
  - entity_id: input_boolean.virtual_chauffage_antoine
    from: 'off'
    platform: state
    to: 'on'
  - below: '26'
    entity_id: input_number.temperature_sol_antoine
    platform: numeric_state
  condition:
  - below: '26'
    condition: numeric_state
    entity_id: input_number.temperature_sol_antoine
  - condition: state
    entity_id: input_boolean.virtual_chauffage_antoine
    state: 'on'
  action:
  - data:
      entity_id: input_boolean.chauffage_antoine
    service: input_boolean.turn_on
- id: '1568230211853'
  alias: chauffage antoine off
  trigger:
  - entity_id: input_boolean.virtual_chauffage_antoine
    from: 'on'
    platform: state
    to: 'off'
  - above: '28'
    entity_id: input_number.temperature_sol_antoine
    platform: numeric_state
  condition: []
  action:
  - data:
      entity_id: input_boolean.chauffage_antoine
    service: input_boolean.turn_off
