- id: backup config
  alias: backup config github
  description: https://github.com/flotre/confighassio
  trigger:
  - platform: time
    at: 02:00:00
  action:
  - service: shell_command.save_config
    data: {}
- id: '1567537848073'
  alias: Alerte intrusion
  trigger:
  - entity_id: binary_sensor.door_window_sensor_chambre_bas
    from: 'off'
    platform: state
    to: 'on'
  - entity_id:
    - binary_sensor.lumi_lumi_sensor_magnet_aq2_b731b502_on_off
    from: 'off'
    platform: state
    to: 'on'
  - entity_id:
    - binary_sensor.lumi_lumi_sensor_magnet_aq2_116bb502_on_off
    from: 'off'
    platform: state
    to: 'on'
  - entity_id:
    - binary_sensor.lumi_lumi_sensor_magnet_aq2_on_off
    from: 'off'
    platform: state
    to: 'on'
  - entity_id:
    - binary_sensor.lumi_lumi_sensor_magnet_aq2_cc21e703_on_off
    from: 'off'
    platform: state
    to: 'on'
  - entity_id:
    - binary_sensor.lumi_lumi_sensor_magnet_aq2_2948e703_on_off
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.contact_porte_garage
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: person.alice
    state: not_home
  - condition: state
    entity_id: person.florent
    state: not_home
  action:
  - data_template:
      message: "Une porte ou une fenetre est ouverte mais personne n'est présent {%
        for state in states.binary_sensor %}\n  {% if state.state == 'on' %}\n    {{
        state.entity_id }}={{ state.state }},\n  {% endif %}\n{% endfor %}\n"
      title: Alerte intrusion
    service: notify.email
- id: '1568061925733'
  alias: Backup
  trigger:
  - hours: '2'
    minutes: '30'
    platform: time_pattern
    seconds: '0'
  condition: []
  action:
  - service: hassio.backup_full
    data: {}
- id: '1568229466238'
  alias: chauffage antoine on
  trigger:
  - entity_id: input_boolean.virtual_chauffage_antoine
    from: 'off'
    platform: state
    to: 'on'
  - below: '25'
    entity_id: sensor.lumi_lumi_weather_temperature
    platform: numeric_state
  condition:
  - below: '26'
    condition: numeric_state
    entity_id: sensor.lumi_lumi_weather_temperature
  - condition: state
    entity_id: input_boolean.virtual_chauffage_antoine
    state: 'on'
  action:
  - data:
      entity_id: switch.radiateur_chambre_antoine
    service: switch.turn_on
- id: '1568230211853'
  alias: chauffage antoine off
  trigger:
  - entity_id: input_boolean.virtual_chauffage_antoine
    from: 'on'
    platform: state
    to: 'off'
  - above: '27'
    entity_id: sensor.lumi_lumi_weather_temperature
    platform: numeric_state
  condition: []
  action:
  - data:
      entity_id: switch.radiateur_chambre_antoine
    service: switch.turn_off
- id: '1574280838904'
  alias: chauffage salon
  trigger:
  - platform: template
    value_template: '{{ is_state_attr("climate.salon", "preset_mode", "comfort") }}'
  - platform: template
    value_template: '{{ is_state_attr("climate.entree", "preset_mode", "comfort")
      }}'
  - platform: template
    value_template: '{{ is_state_attr("climate.cuisine", "preset_mode", "comfort")
      }}'
  condition: []
  action:
  - data:
      entity_id: climate.entree
      preset_mode: comfort
    service: climate.set_preset_mode
  - data:
      entity_id: climate.cuisine
      preset_mode: comfort
    service: climate.set_preset_mode
  - data:
      entity_id: climate.salon
      preset_mode: comfort
    service: climate.set_preset_mode
- id: '1668629795314'
  alias: Low battery level detection & notification for all battery sensors
  description: ''
  use_blueprint:
    path: gmlupatelli/low_battery_notification.yaml
    input:
      threshold: 30
      actions:
      - service: persistent_notification.create
        data:
          message: '{{sensors}}'
          title: Alerte batterie
- id: '1674389488356'
  alias: chauffage SDE ON
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.switch_sde_humidite
    - switch.switch_sde_temperature
    from: 'off'
    to: 'on'
  condition: []
  action:
  - data: {}
    target:
      entity_id: switch.radiateur_sde
    action: switch.turn_on
  mode: single
- id: '1674389648731'
  alias: Chauffage SDE OFF
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.switch_sde_humidite
    - switch.switch_sde_temperature
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: switch.switch_sde_humidite
      state: 'off'
    - condition: state
      entity_id: switch.switch_sde_temperature
      state: 'off'
  action:
  - data: {}
    target:
      entity_id: switch.radiateur_sde
    action: switch.turn_off
  mode: single
