
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

logger:
  default: info
  logs:
    homeassistant.components.mqtt: info
    custom_components.generic_smart_thermostat.climate: debug


schedule_list:

webhook:


# Example configuration.yaml entry
notify:
  - name: email
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: !secret florent_email
    encryption: starttls
    username: !secret florent_email
    password: !secret gmail_password
    recipient:
      - !secret florent_email
      - !secret alice_email
    sender_name: My Home Assistant

# Exposes service shell_command.save_config
shell_command:
  save_config: git commit -a -m "auto backup"; git push



sensor:
  - platform: template
    sensors:
      unavailable_entities:
        friendly_name: Unavailable Entities
        unit_of_measurement: entities
        icon_template: "{{ 'mdi:check-circle' if is_state('sensor.unavailable_entities','0') else 'mdi:alert-circle' }}"
        value_template: >
          {{ states|selectattr('state','in',['unavailable','unknown','none'])|rejectattr('domain','eq','group')
            |list|count }}
        attribute_templates:
          entities: >
            {{ states|selectattr('state','in',['unavailable','unknown','none'])|rejectattr('domain','eq','group')
              |map(attribute='entity_id')|join(',') }}

    
input_boolean:
  virtual_chauffage_antoine:
    name: Etat souhaite du chauffage
    icon: mdi:radiator



climate:
  - platform: generic_smart_thermostat
    name: Salon
    heater: switch.radiateur_salon
    in_temp_sensor: sensor.lumi_lumi_weather_88e47101_temperature
    out_temp_sensor: sensor.temperature_exterieur
    use_schedule_list: true
    preheat: true
    calculate_period: 60
    
  - platform: generic_smart_thermostat
    name: Entrée
    heater: switch.radiateur_entree
    in_temp_sensor: sensor.lumi_lumi_weather_f758f501_temperature
    out_temp_sensor: sensor.temperature_exterieur
    use_schedule_list: true
    preheat: true
    calculate_period: 60

  - platform: generic_smart_thermostat
    name: Cuisine
    heater: switch.radiateur_cuisine
    in_temp_sensor: sensor.lumi_lumi_weather_6438fa01_temperature
    out_temp_sensor: sensor.temperature_exterieur
    use_schedule_list: true
    preheat: true
    calculate_period: 60
    
  - platform: generic_smart_thermostat
    name: Salle deau
    heater: switch.radiateur_sde
    in_temp_sensor: sensor.lumi_lumi_weather_7ce37101_temperature
    out_temp_sensor: sensor.temperature_exterieur
    confort_temp: 22
    use_schedule_list: true
    preheat: true

  - platform: generic_smart_thermostat
    name: Chambre Antoine
    heater: input_boolean.virtual_chauffage_antoine
    in_temp_sensor: sensor.lumi_lumi_weather_7a870102_weather_chambre_antoine
    out_temp_sensor: sensor.temperature_exterieur
    use_schedule_list: true
    preheat: true
    calculate_period: 30
    confort_temp: 19
  
  - platform: generic_smart_thermostat
    name: Chambre bas
    heater: switch.radiateur_chambre_bas
    in_temp_sensor: sensor.lumi_lumi_weather_dc820102_temperature
    out_temp_sensor: sensor.temperature_exterieur
    use_schedule_list: true
    preheat: true
    calculate_period: 30
    confort_temp: 19
    